In [47]:
import numpy as np

In [48]:
# 1. Write a function so that the columns of the output matrix are powers of the input vector.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.(N - i - 1)

def vander(x):
    ls = [ x**(len(x)-i-1) for i in range(len(x))]
    mat = np.array(ls).T
    print(mat)
    
if __name__ == '__main__':
    arr = np.array([3,5,7,9])
    vander(arr)


[[ 27   9   3   1]
 [125  25   5   1]
 [343  49   7   1]
 [729  81   9   1]]


In [49]:
# 2. Write a function to find moving average in an array over a window:
# Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.


def moving_avg(ls,N,K):
    res = []
    for i in range(N-K+1):
        val = round(np.mean(ls[i:i+K]),2)
        res.append(val)
    print(res)
    
if __name__ == '__main__':
    arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
    n = len(arr)
    k = 3
    moving_avg(arr,n,k)


[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
